### PR TITLE
Fixed issue with unban award

### PR DESCRIPTION
**Pull request by scitzocel**
Fixed issue where unban award does not work for shadowbanned users

### CODE REVIEW

**Comment by Aevann1** [comment]
haha

**Comment by scitzocel** [comment]
> haha

Scitzocel stuck in shadowban coping and seething 😡 😡 😡

**Comment by Aevann1** [comment]
I unshadowbanned u, DM me on the site if this happens again

**Comment by Aevann1** [comment]
I'm @Aevann

**Pull request closed without merging**
