### PR TITLE
Make username regex consistent between frontend and backend

### PR DESCRIPTION
**Pull request by rvs314**
Ensures the regex used for verifying the username is the same between the frontend and backend by passing it as a template parameter.

## Description
What it says on the tin - just passes the `valid_username_regex` as a parameter to `signup.html` template and replaces the copied regex in the input form. It also adds hyphens to the username regex á la reddit.

## Motivation and Context
My normal username has hyphens, which don't work right now. It seems to just be a problem with the regex, though I may be dumb and not have seen something else.

## How Has This Been Tested?
Not at all lmao, though it seems you guys aren't exactly doing TDD here. I wasn't able to get the app to build on my machine, so I imagine you'll have to run it on yours to ensure it doesn't throw a syntax error or something. BTW, if you want people to help, adding instructions on how to run the app would be nice.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by IThinkImOKAY** [comment]
Your code will not work.

https://github.com/rvs314/Drama/blob/master/ruqqus/routes/login.py#L235

You are missing a comma.

**Comment by rvs314** [comment]
Should be fixed (although it'd be better to be able to actually run the code)

**Comment by Aevann1** [comment]
Thanks mate, I made it consistent manually

**Comment by rvs314** [comment]
This still doesn't allow for hyphens in usernames, which was the point of the patch. People switching over from reddit who want to use their current username need hyphens, which Reddit supports

**Comment by IThinkImOKAY** [comment]
>I made it consistent manually

No, you didn't 🐪

**Comment by Aevann1** [comment]
done

**Comment by rvs314** [comment]
This has to be changed as well: https://github.com/Aevann1/Drama/blob/master/ruqqus/assets/js/all_js.js#L798

**Comment by Aevann1** [comment]
good catch

>

**Comment by IThinkImOKAY** [comment]
🐪

**Pull request closed without merging**
