### PR TITLE
dramacoin transfers

### PR DESCRIPTION
**Pull request by atrc445**
todo: how to call officially call the transfers, breaking changes? possibly more
done: transfers, registering transfers, rate limits, frontend, notifications, basic error handling

if anyone has any notes about the changes please post here

### CODE REVIEW

**Comment by Aevann1** [comment]
There's no need for a new table, king

**Comment by atrc445** [comment]
its not just for rate limiting, i thought logging all the transactions could come in useful in the future 

also, i implemented rate limitng (one transaction per receiver per ten minutes) to prevent people from spamming notifications. what do you think about this? i also considered a) not giving a fuck about spam b) removing gift notifications entirely

**Comment by Aevann1** [comment]
I'm partial to just adding a minimum of dramacoin transfers (maybe 500) to
prevent spam instead

**Comment by atrc445** [comment]
ok that sounds cool too. i will go with 100 for now and you can adjust this later. removing the table for now.

**Comment by Aevann1** [comment]
thank you king

**Comment by atrc445** [comment]
im not going to add anything more to this (unless something is missing) so feel free to merge when you are ready

**Review by Aevann1 — APPROVED** [review]

**Comment by Aevann1** [comment]
Very nice job, king, thank you 😘

**Pull request merged**
